### ISSUE TITLE
ObjectFiller fails to fill IReadOnlyCollection

### ISSUE THREAD

**Issue by oliverhanappi** [Tynamix/ObjectFiller.NET#91]
Given the following class:

    public class Order
    {
        public IReadOnlyCollection<string> OrderLines { get; set; }
    }

Filling it by running the following code fails.

    var filler = new Filler<Order>();
    var order = filler.Create();

The following exception is thrown:

    System.InvalidOperationException: This operation is only valid on generic types.
       at System.RuntimeType.GetGenericTypeDefinition()
       at Tynamix.ObjectFiller.Filler`1.<>c.<TypeIsCollection>b__13_0(Type x)
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
       at Tynamix.ObjectFiller.Filler`1.TypeIsCollection(Type type)
       at Tynamix.ObjectFiller.Filler`1.CreateAndFillObject(Type type, FillerSetupItem currentSetupItem, HashStack`1 typeTracker)
       at Tynamix.ObjectFiller.Filler`1.FillInternal(Object objectToFill, HashStack`1 typeTracker)
       at Tynamix.ObjectFiller.Filler`1.Create()

Using an `ICollection<string>` instead works.

**Comment by Tynamix** [comment]
Fixed, will be released with next version. Thank you for reporting this issue!
